{{- $secretName := include "wordpress.fullname" . -}}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
{{- if not .Values.wordpress.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ (and $existingSecret $existingSecret.data (index $existingSecret.data "mariadb-root-password")) | default (randAlphaNum 24 | b64enc) | quote }}
  mariadb-password: {{ (and $existingSecret $existingSecret.data (index $existingSecret.data "mariadb-password")) | default (randAlphaNum 24 | b64enc) | quote }}
  mariadb-host: {{ include "wordpress.mariadb.fullname" . | b64enc | quote }}
{{- end }}
