{{- if not .Values.wordpress.existingSecret }}
{{- $secretName := include "wordpress.fullname" . -}}
{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ if $existingSecret }}{{ index $existingSecret.data "mariadb-root-password" }}{{ else }}{{ randAlphaNum 24 | b64enc | quote }}{{ end }}
  mariadb-password: {{ if $existingSecret }}{{ index $existingSecret.data "mariadb-password" }}{{ else }}{{ randAlphaNum 24 | b64enc | quote }}{{ end }}
  mariadb-host: {{ include "wordpress.mariadb.fullname" . | b64enc | quote }}
{{- end }}
